export const multiSelectInputDefaultClasses = {
    container:
        "relative mx-auto w-full bg-gray-50 dark:bg-gray-700 dark:text-white flex items-center justify-end box-border cursor-pointer dark:border-gray-600 border border-gray-300 rounded-lg text-base leading-snug outline-hidden",
    containerDisabled: "cursor-default bg-gray-100",
    containerOpen: "rounded-b-none",
    containerOpenTop: "rounded-t-none",
    containerActive: "border-gray-500 ring-1 ring-gray-500 dark:focus:border-gray-400 dark:focus:ring-gray-400",
    wrapper: "relative mx-auto w-full flex items-center justify-end box-border cursor-pointer outline-hidden",
    singleLabel:
        "flex items-center h-full max-w-full absolute left-0 top-0 pointer-events-none bg-transparent leading-snug pl-3.5 pr-16 box-border rtl:left-auto rtl:right-0 rtl:pl-0 rtl:pr-3.5",
    singleLabelText: "text-ellipsis overflow-hidden block whitespace-nowrap max-w-full",
    multipleLabel:
        "flex items-center h-full absolute left-0 top-0 pointer-events-none bg-transparent leading-snug pl-3.5 rtl:left-auto rtl:right-0 rtl:pl-0 rtl:pr-3.5",
    search: "w-full absolute inset-0 outline-hidden focus:ring-0 appearance-none box-border border-0 text-base font-sans bg-white rounded-xs pl-3.5 rtl:pl-0 rtl:pr-3.5",
    tags: "grow shrink flex flex-wrap items-center mt-1 pl-2 min-w-0 rtl:pl-0 rtl:pr-2",
    tag: "bg-primary-600 text-white text-sm font-medium py-0.5 pl-2 rounded-xs mr-1 mb-1 flex items-center whitespace-nowrap",
    tagDisabled: "pr-2 opacity-75",
    tagWrapper: "whitespace-nowrap overflow-hidden text-ellipsis",
    tagWrapperBreak: "whitespace-normal break-all",
    tagRemove: "flex items-center justify-center p-1 mx-0.5 rounded-xs hover:bg-black/10 group",
    // tagRemoveIcon: "bg-multiselect-remove bg-center bg-no-repeat opacity-30 inline-block w-3 h-3 group-hover:opacity-60",
    tagsSearchWrapper: "inline-block relative mx-1 mb-1 grow shrink h-full",
    tagsSearch: "absolute inset-0 border-0 outline-hidden focus:ring-0 appearance-none p-0 text-base font-sans box-border w-full",
    tagsSearchCopy: "invisible whitespace-pre-wrap inline-block h-px",
    placeholder:
        "flex items-center h-full absolute text-sm left-0 top-0 pointer-events-none bg-transparent leading-snug pl-3.5 text-gray-900 dark:text-white",
    caret: "bg-light-arrow-pattern bg-center bg-cover bg-no-repeat w-3 h-3 mr-3 relative z-10 pointer-events-none",
    caretOpen: "rotate-180 pointer-events-auto",
    clear: "pr-3.5 relative z-10 opacity-40 transition duration-300 shrink-0 grow-0 flex hover:opacity-80 rtl:pr-0 rtl:pl-3.5",
    // clearIcon: "bg-multiselect-remove bg-center bg-no-repeat w-2.5 h-4 py-px box-content inline-block",
    // spinner: "bg-multiselect-spinner bg-center bg-no-repeat w-4 h-4 z-10 mr-3.5 animate-spin shrink-0 grow-0 rtl:mr-0 rtl:ml-3.5",
    infinite: "flex items-center justify-center w-full",
    // infiniteSpinner: "bg-multiselect-spinner bg-center bg-no-repeat w-4 h-4 z-10 animate-spin shrink-0 grow-0 m-3.5",
    dropdown:
        "max-h-60 absolute -left-px -right-px bottom-0 transform translate-y-full border border-gray-300 dark:border-gray-500 -mt-px overflow-y-scroll z-50 bg-white dark:bg-gray-700 flex flex-col rounded-b-lg",
    dropdownTop: "-translate-y-full top-px bottom-auto rounded-b-none rounded-t-sm",
    dropdownHidden: "hidden",
    options: "flex flex-col p-0 m-0 list-none",
    optionsTop: "",
    group: "p-0 m-0",
    groupLabel: "flex text-sm box-border items-center justify-start text-left py-1 px-3 font-semibold bg-gray-200 text-primary-600 cursor-default leading-normal",
    groupLabelPointable: "cursor-pointer",
    groupLabelPointed: "bg-gray-300 text-gray-700",
    groupLabelSelected: "bg-primary-600 text-white",
    groupLabelDisabled: "bg-gray-100 text-gray-300 cursor-not-allowed",
    groupLabelSelectedPointed: "bg-primary-600 text-white opacity-80",
    groupLabelSelectedDisabled: "text-green-100 bg-green-600/50 cursor-not-allowed",
    groupOptions: "pl-2 m-0",
    option: "flex items-center justify-start box-border text-left cursor-pointer text-sm leading-snug py-2 px-3",
    optionPointed: "bg-gray-100 dark:bg-gray-600",
    optionSelected: "text-white bg-green-500",
    optionDisabled: "text-gray-300 cursor-not-allowed dark:text-gray-500",
    optionSelectedPointed: "text-white bg-green-500 opacity-90",
    optionSelectedDisabled: "text-green-100 bg-green-500/50 cursor-not-allowed",
    noOptions: "py-2 px-3 text-gray-600 bg-white text-left rtl:text-right",
    noResults: "py-2 px-3 text-gray-600 bg-white dark:text-gray-400 dark:bg-gray-700 text-left rtl:text-right",
    fakeInput: "bg-transparent absolute left-0 right-0 -bottom-px w-full h-px border-0 p-0 appearance-none outline-hidden text-transparent",
    assist: "absolute -m-px w-px h-px overflow-hidden",
    spacer: "h-9 py-px box-content",
};

export const discordIdRegex = /^\d{17,20}$/;
export const rsiHandleRegex = /^\S{3,64}$/;
