name: node build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Node 18 build
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci # install dependencies
      - run: npm run build # compile typescript
      - run: npm run lint # run eslint
      - run: npm run prettier  # run prettier
#      - run: npm test # commented out as tests are not added to the repo yet - tests should be added in the future
