name: node build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Node 22 build
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm ci # install dependencies
      - run: npm run build # compile typescript
      - run: npm run lint # run eslint
      - run: npm run format  # run prettier
